id = "vs-code-2026-theme"
name = "VS Code 2026"
description = "A port of the VS Code 2026 light and dark themes for Zed"
version = "0.2.0"
schema_version = 1
authors = ["Mustafa Yurdakul"]
repository = "https://github.com/mustafayurdakul/vs-code-2026-theme-for-zed"
